name: test-setup-llvm-msvc

on: [push, pull_request]

jobs:
  build:
    # Skip building pull requests from the same repository.
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: windows-latest
    steps:
      - uses: NewWorldComingSoon/setup-llvm-msvc@v1
